wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711344593.925075
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 83
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 83
      3:
      - 2
      - 13
      - 23
      4: 3.10.11
      5: 0.15.5
      6: 4.35.2
      8:
      - 5
run_name:
  desc: null
  value: 400-100-80
randomize_seed:
  desc: null
  value: false
gen_seed:
  desc: null
  value: 0
guidance_scale:
  desc: null
  value: 1
dataset:
  desc: null
  value: Gustavosta/Stable-Diffusion-Prompts
start:
  desc: null
  value: 0
end:
  desc: null
  value: 10
decoder_inv_steps:
  desc: null
  value: 400
forward_steps:
  desc: null
  value: 100
tuning_steps:
  desc: null
  value: 80
reg_coeff:
  desc: null
  value: 0.0
with_tracking:
  desc: null
  value: true
